// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_applicationcontroller.cpp"
#include "EWIEGA46WW/moc_auditorycontroller.cpp"
#include "EWIEGA46WW/moc_blockcontroller.cpp"
#include "EWIEGA46WW/moc_studentsgroupcontroller.cpp"
#include "EWIEGA46WW/moc_subjectcontroller.cpp"
#include "EWIEGA46WW/moc_teachercontroller.cpp"
#include "EWIEGA46WW/moc_timeslotcontroller.cpp"
#include "EWIEGA46WW/moc_timetablecontroller.cpp"
