// This file is autogenerated. Changes will be overwritten.
#include "U7BSQOHBDD/moc_auditoryobject.cpp"
#include "U7BSQOHBDD/moc_blockobject.cpp"
#include "U7BSQOHBDD/moc_studentsgroupobject.cpp"
#include "U7BSQOHBDD/moc_subjectobject.cpp"
#include "U7BSQOHBDD/moc_teacherobject.cpp"
#include "U7BSQOHBDD/moc_timeslotobject.cpp"
#include "U7BSQOHBDD/moc_timetableobject.cpp"
